import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import Nav from "../../components/Nav/Nav";
import { Cat } from "../../data";
import DefaultLayout from "../../layouts/Default";

export default function CatCard() {
  const router = useRouter();
  const { id } = router.query;
  const [cat, setCat] = useState<Cat>();

  const fecthCat = async () => {
    const response = await fetch(`/api/cats/${id}`);
    const data = await response.json();
    setCat(data);
  };

  useEffect(() => {
    fecthCat();
  }, [id]);

  return (
    <>
      <DefaultLayout>
        <div>
          {cat && (
            <>
              <Head>
                <title>{cat.name}</title>
                <meta
                  name='description'
                  content='Generated by React and NextJs'
                />
                <link rel='icon' href='/favicon.ico' />
              </Head>
              <div className='container mt-5' style={{ display: "flex" }}>
                <img src={cat.image.url} alt={cat.image.alt} />
                <div className='mx-5'>
                  <h1>{cat.name}</h1>
                  <p>{cat.description}</p>
                </div>
              </div>
            </>
          )}
        </div>
      </DefaultLayout>
    </>
  );
}
