import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav/Nav";
import Jumbotron from "../components/Jumbotron/Jumbotron";
import DefaultLayout from "../layouts/Default";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cats World by React and NextJs</title>
        <meta name='description' content='Generated by React and NextJs' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <DefaultLayout>
        <Jumbotron></Jumbotron>
      </DefaultLayout>

      <footer></footer>
    </div>
  );
};

export default Home;
